# Generated by Django 6.0.4 on 2026-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='saved_at',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='user_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedjob',
            name='user_name',
            field=models.CharField(default='romer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
