# Generated by Django 6.0.4 on 2026-04-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userprofile_remove_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
