# Generated by Django 6.0.4 on 2026-04-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_employerprofile_employerjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_jobs', to='jobs.employerprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_direct_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
