# Generated by Django 5.2.13 on 2026-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
